# Generated by Django 6.0.1 on 2026-02-22

import uuid
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('default_period', models.CharField(choices=[('today', 'Today'), ('week', 'This Week'), ('month', 'This Month'), ('quarter', 'This Quarter'), ('year', 'This Year')], default='month', help_text='Default time period for reports.', max_length=10, verbose_name='Default Period')),
                ('default_currency', models.CharField(default='EUR', help_text='Currency code for report display.', max_length=3, verbose_name='Default Currency')),
                ('show_profit', models.BooleanField(default=True, help_text='Show profit/margin data in reports.', verbose_name='Show Profit')),
                ('show_tax_breakdown', models.BooleanField(default=False, help_text='Show detailed tax breakdown in reports.', verbose_name='Show Tax Breakdown')),
                ('compare_previous_period', models.BooleanField(default=True, help_text='Show comparison with previous period.', verbose_name='Compare Previous Period')),
                ('fiscal_year_start_month', models.IntegerField(default=1, help_text='Month when the fiscal year starts (1=January, 12=December).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fiscal Year Start Month')),
            ],
            options={
                'db_table': 'analytics_settings',
                'verbose_name': 'Analytics Settings',
                'verbose_name_plural': 'Analytics Settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('report_type', models.CharField(choices=[('sales', 'Sales'), ('products', 'Products'), ('customers', 'Customers'), ('custom', 'Custom')], default='sales', max_length=20, verbose_name='Report Type')),
                ('config', models.JSONField(default=dict, help_text='Report configuration: filters, columns, grouping', verbose_name='Configuration')),
                ('created_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to='accounts.localuser', verbose_name='Created By')),
                ('is_shared', models.BooleanField(default=False, help_text='Make this report visible to all employees.', verbose_name='Shared')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
            ],
            options={
                'db_table': 'analytics_saved_report',
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('report_type', models.CharField(max_length=50, verbose_name='Report Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('is_stale', models.BooleanField(default=False, verbose_name='Is Stale')),
            ],
            options={
                'db_table': 'analytics_snapshot',
                'verbose_name': 'Report Snapshot',
                'verbose_name_plural': 'Report Snapshots',
                'abstract': False,
                'indexes': [
                    models.Index(fields=['hub_id', 'report_type', 'period_start', 'period_end'], name='analytics_snap_hub_type_period'),
                ],
            },
        ),
    ]
